### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by RicardoGCCR** [EnzoAndree/FastMLST#8]
Hi Enzo!
How are you!?

I recently install fastMLST in a new PC, and I am getting the following error:
  File "/home/rgutierrez/mambaforge/envs/fastMLST/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

Any idea what is going on?

Thanks,
Ricardo

**Comment by EnzoAndree** [comment]
Hi Ricardo,

I'm sorry to hear you're experiencing issues with fastMLST on your new PC. The error message you're seeing (HTTP Error 429: Too Many Requests) suggests that the PubMLST server is temporarily blocking your requests due to a high volume of queries.

To resolve this, you can try limiting the number of concurrent requests fastMLST makes by using the `-t` flag to reduce the number of threads. Here are a couple of suggestions:

1. Try running fastMLST with `-t 2` to limit it to two threads:
   ```
   fastmlst -t 2 [other options]
   ```

2. If that still doesn't work, you can try limiting it to a single thread with `-t 1`:
   ```
   fastmlst -t 1 [other options]
   ```

These adjustments should reduce the load on the PubMLST server and hopefully allow your queries to go through without being blocked.

Important note: Once you've successfully downloaded the database, you can then use as many threads as you want for subsequent analyses. The thread limitation is only necessary for the initial database download to avoid overwhelming the PubMLST server.

Let me know if this helps or if you need any further assistance!

Best regards,
Enzo

**Comment by RicardoGCCR** [comment]
Hi Enzo, 
Thank you for getting back to me so quickly!
It worked perfectly with -t 4 (as with -t2 I got a connection time-out error)
Thanks again
Ricardo
